{{- range $service := (list "api" "pubsub") }}
{{- $serviceValues := index $.Values.backend $service }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "DOChart.componentname" (list $ (printf "%s-deployment" $service)) }}
  labels: {{- include (printf "DOChart.labels.backend.%s" $service) (list $ (printf "%s-deployment" $service)) | nindent 4 }}
spec:
  replicas: {{ default $.Values.backend.replicaCount $serviceValues.replicaCount }}
  selector:
    matchLabels: {{- include ( printf "DOChart.labels.backend.%s" $service) (list $ (printf "%s-deployment" $service)) | nindent 6 }}
  template:
    metadata:
      labels: {{- include ( printf "DOChart.labels.backend.%s" $service) (list $ (printf "%s-deployment" $service)) | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ $serviceValues.imagePullSecrets }}
      serviceAccountName: {{ include "DOChart.serviceAccountName" $ }}
      containers:
        - name: {{ $.Chart.Name }}-{{ $service }}
          image: "{{ $serviceValues.image }}:{{ $serviceValues.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" $serviceValues.imagePullPolicy }}
          env:
            {{- range $envvars := $serviceValues.envList }}
            - name: {{ $envvars }}
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-secret" $service }}
                  key: {{ $envvars }}
            {{- end }}
          ports:
            - name: {{ (printf "%s-port" $service) }}
              containerPort: {{ $serviceValues.port }}
              protocol: TCP
---
{{ end }}
