{{- range $service := (list "api") }}
{{- $serviceValues := index $.Values.backend $service }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "DOChart.componentname" (list $ (printf "%s-ingress" $service)) }}
  labels: {{- include ( printf "DOChart.labels.backend.%s" $service) (list $ (printf "%s-ingress" $service)) | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: production-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ $serviceValues.host }}
      secretName: {{ printf "%s-tls" $service }}
  defaultBackend:
    service:
      name: {{ include "DOChart.componentname" (list $ (printf "react-service")) }}
      port:
        name: {{ printf "react-port" }}
  rules:
    - host: {{ $serviceValues.host }}
      http:
        paths:
          - path: /v0
            pathType: Prefix
            backend:
              service:
                name: {{ include "DOChart.componentname" (list $ (printf "%s-service" $service)) }}
                port:
                  name: {{ printf "%s-port" $service }}
{{ end }}
