CREATE TABLE users(
	id SERIAL PRIMARY KEY,
	name text NOT NULL,
  	email text NOT NULL,
  	password text NOT NULL,
  	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

