CREATE TABLE IF NOT EXISTS top_content(
	id SERIAL PRIMARY KEY NOT NULL,
	ticker text NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	url text NOT NULL,
	src text NOT NULL
);
