// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Sources        string
	SpatialRefSys  string
	StockSentiment string
	Tickers        string
	TopContent     string
	Users          string
}{
	Sources:        "sources",
	SpatialRefSys:  "spatial_ref_sys",
	StockSentiment: "stock_sentiment",
	Tickers:        "tickers",
	TopContent:     "top_content",
	Users:          "users",
}
